apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kbe-rest-brewery
  name: kbe-rest-brewery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbe-rest-brewery
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kbe-rest-brewery
    spec:
      containers:
      - image: local/kbe-rest-brewery:0.0.1-SNAPSHOT
        name: kbe-rest-brewery
        resources: {}
        env:
          - name: LOGGING_LEVEL_ORG_ZALANDO_LOGBOOK
            value: "TRACE"
          - name: SERVER_SHUTDOWN
            value: "graceful"
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3    
status: {}
