apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kbe-rest-brewery
  name: kbe-rest-brewery
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kbe-rest-brewery
  #type: ClusterIP
  type: NodePort
status:
  loadBalancer: {}
